---
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - GO111MODULE=on
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: arnested
      name: homebrew-ssh2iterm2
    directory: Formula
    homepage: "https://github.com/arnested/ssh2iterm2"
    description: "Create iTerm2 dynamic profile from SSH config"
    install: |
      bin.install "ssh2iterm2"
    service: |
      run [opt_bin/"ssh2iterm2", "watch"]
      keep_alive true
