before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - GO111MODULE=on
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X main.GitSummary={{ .Version }}
    flags:
      - -trimpath

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: arnested
      name: homebrew-ssh2iterm2
    folder: Formula
    homepage: "https://github.com/arnested/ssh2iterm2"
    description: "Create iTerm2 dynamic profile from SSH config"
    install: |
      bin.install "ssh2iterm2"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
          <key>Label</key>
          <string>#{plist_name}</string>
          <key>ProgramArguments</key>
          <array>
            <string>#{opt_bin}/ssh2iterm2</string>
            <string>watch</string>
          </array>
          <key>RunAtLoad</key>
          <true/>
          <key>KeepAlive</key>
          <true/>
        </dict>
      </plist>
