---
name: Lint
on:
  - pull_request
  - push

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    name: GitHub Actions workflow
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
  markdownlint:
    name: Markdown
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
  yamllint:
    name: YAML
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Yamllint
        uses: frenck/action-yamllint@v1.5.0
        with:
          strict: true
